name: Create release when tag is pushed

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1
        with:
          generateReleaseNotes: true
          name: '${{ github.ref_name }}'
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}