name: Create release when tag is pushed

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: ncipollo/release-action@bcfe5470707e8832e12347755757cec0eb3c22af # v1
        with:
          generateReleaseNotes: true
          name: '${{ github.ref_name }}'
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}